name: pipeline
on:
  push:
    branches: [main]
  pull_request:
jobs:
  terraform:
    runs-on: self-hosted
    environment: vmcreation
    steps:
      - name: Verify Terraform
        run: terraform -version

      - name: Verify Azure CLI
        shell: powershell
        run: az --version

      - name: Azure login with Service Principal
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          client-secret: ${{ secrets.ARM_CLIENT_SECRET }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Terraform Init
        shell: powershell
        run: terraform init

      - name: Terraform Validate
        shell: powershell
        run: terraform validate

      - name: Terraform Plan
        shell: powershell
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        shell: powershell
        run: terraform apply -auto-approve tfplan

      - name: Terraform Output
        shell: powershell
        run: terraform output
